amcl:
  ros__parameters:
    use_sim_time: True
    base_frame_id: "base_footprint"
    global_frame_id: "map"
    odom_frame_id: "odom"
    scan_topic: "scan"

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: True
    planner_plugins: ["WeightedAStar"]

    WeightedAStar:
      plugin: "nav2_weighted_astar_planner/WeightedAStarPlanner"
      tolerance: 0.5
      allow_unknown: false

controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 20.0
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      max_vel_x: 0.26
      max_vel_theta: 1.0
      acc_lim_x: 2.5
      acc_lim_theta: 3.2
      sim_time: 1.7
      critics: ["RotateToGoal", "PathAlign", "PathDist", "GoalDist"]
